version: "3"
services:
  nginx:
    build: ./requirements/nginx
    image:  nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
     - vol-wp_file:/var/www/html
    depends_on:
     - wordpress
    networks:
      inception_network:
  mariadb:
    build: ./requirements/mariadb
    image:  mariadb
    container_name: mariadb
    restart:  always
    env_file: .env
    ports:
      - "3306"
    volumes:
     - vol-wp_db:/var/lib/mysql
    networks:
      inception_network:
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    ports:
      - "9000"
    volumes:
      - vol-wp_file:/var/www/html
    env_file: .env
    restart: always
    networks:
      inception_network:


volumes:
  vol-wp_file:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/houbeid/data/vol-wp_file
  vol-wp_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/houbeid/data/vol-wp_db




networks:
  inception_network:
